// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dashboard/overview": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "สรุปตัวเลขบนแดชบอร์ด: จำนวนคำขอทั้งหมด/รออนุมัติ/อนุมัติ/ไม่อนุมัติ, ข้อมูล pie (approved vs waiting) และสถิติรายฝ่าย (พนักงานเข้าใหม่/ลาออก)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Dashboard overview",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DashboardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "ตรวจสอบผู้ใช้และคืน JWT token (แนบใน Authorization: Bearer \u003ctoken\u003e)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login and get JWT token",
                "parameters": [
                    {
                        "description": "email \u0026 password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/requests": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ดึงรายการ manpower requests ตามสิทธิ์ (Admin/Approve เห็นทั้งหมด, User เห็นเฉพาะกอง/แผนกตัวเอง)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Get all manpower requests",
                "responses": {
                    "200": {
                        "description": "data: []ManpowerRequest",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/requests/submit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ผู้ใช้สร้างคำขอและส่งเข้ากระบวนการอนุมัติทันที (origin_status=SUBMITTED)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Requests"
                ],
                "summary": "Create \u0026 submit manpower request",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateManpowerRequestInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateSubmitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/requests/{id}/decide": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ผู้อนุมัติตาม lane ของตัวเอง ทำการตัดสินใจในคำขอ (APPROVE / REJECT / RETURN)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Approvals"
                ],
                "summary": "Approve/Reject/Return a request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "request_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "action: APPROVE | REJECT | RETURN",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.DecideRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.DecideResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CreateManpowerRequestInput": {
            "type": "object",
            "required": [
                "contract_type_id",
                "employment_type_id",
                "num_required",
                "reason_id",
                "required_position_name"
            ],
            "properties": {
                "contract_type_id": {
                    "type": "integer"
                },
                "education_level_id": {
                    "type": "integer"
                },
                "employment_type_id": {
                    "type": "integer"
                },
                "experience_id": {
                    "type": "integer"
                },
                "gender_id": {
                    "type": "integer"
                },
                "max_age": {
                    "type": "integer"
                },
                "min_age": {
                    "type": "integer"
                },
                "nationality_id": {
                    "type": "integer"
                },
                "num_required": {
                    "type": "integer"
                },
                "reason_id": {
                    "type": "integer"
                },
                "required_position_name": {
                    "type": "string"
                },
                "special_qualifications": {
                    "type": "string"
                },
                "target_hire_date": {
                    "description": "รูปแบบ YYYY-MM-DD",
                    "type": "string"
                }
            }
        },
        "handlers.CreateSubmitResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-10-12T15:12:00Z"
                },
                "created_by": {
                    "type": "string",
                    "example": "E101"
                },
                "doc_number": {
                    "type": "string",
                    "example": "PQ25100001"
                },
                "hr_status": {
                    "type": "string",
                    "example": "NONE"
                },
                "message": {
                    "type": "string",
                    "example": "Submitted successfully"
                },
                "origin_status": {
                    "type": "string",
                    "example": "SUBMITTED"
                },
                "overall_status": {
                    "type": "string",
                    "example": "IN_PROGRESS"
                },
                "request_id": {
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "handlers.DecideRequest": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "description": "APPROVE / REJECT / RETURN",
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                }
            }
        },
        "handlers.DecideResponse": {
            "type": "object",
            "properties": {
                "doc_number": {
                    "type": "string",
                    "example": "PQ24110026"
                },
                "hr_status": {
                    "type": "string",
                    "example": "WAITING_RECRUITER"
                },
                "message": {
                    "type": "string",
                    "example": "decision stored"
                },
                "origin_status": {
                    "type": "string",
                    "example": "DIR_APPROVED"
                },
                "overall_status": {
                    "type": "string",
                    "example": "IN_PROGRESS"
                },
                "request_id": {
                    "type": "integer",
                    "example": 15
                }
            }
        },
        "models.AuthResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.DashboardPie": {
            "type": "object",
            "properties": {
                "approved": {
                    "type": "integer"
                },
                "waiting": {
                    "type": "integer"
                }
            }
        },
        "models.DashboardResponse": {
            "type": "object",
            "properties": {
                "approval_pie": {
                    "$ref": "#/definitions/models.DashboardPie"
                },
                "per_department": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DeptSeries"
                    }
                },
                "totals": {
                    "$ref": "#/definitions/models.DashboardTotals"
                }
            }
        },
        "models.DashboardTotals": {
            "type": "object",
            "properties": {
                "approved": {
                    "type": "integer"
                },
                "pending": {
                    "type": "integer"
                },
                "rejected": {
                    "type": "integer"
                },
                "requests": {
                    "type": "integer"
                }
            }
        },
        "models.DeptSeries": {
            "type": "object",
            "properties": {
                "dept_id": {
                    "type": "integer"
                },
                "dept_name": {
                    "type": "string"
                },
                "new_hires": {
                    "type": "integer"
                },
                "resigns": {
                    "type": "integer"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "name": "Auth"
        },
        {
            "name": "Requests"
        },
        {
            "name": "Approvals"
        },
        {
            "name": "Dashboard"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Manpower API",
	Description:      "This is a manpower management system API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
